# Emergency minimal configuration for Railway deployment
# Use this if the main app fails to deploy

[providers]
python = "3.11"

[phases.setup]
# Install only FastAPI and uvicorn
cmds = [
  "pip install fastapi==0.109.0 uvicorn[standard]==0.27.0"
]

[start]
# Start minimal app
cmd = "cd backend && uvicorn minimal_main:app --host 0.0.0.0 --port $PORT --log-level info"

[variables]
PYTHONUNBUFFERED = "1"
ENVIRONMENT = "production"