# Railway deployment configuration following best practices
[providers]
python = "3.11"

[phases.build]
workDir = "backend"

[phases.setup]
workDir = "backend"
cmds = [
  "echo 'Starting Python setup... (Updated 2025-08-05)'",
  "echo 'Using main_simple.py for deployment'",
  "pip install --upgrade pip",
  "pip install --no-cache-dir -r requirements.txt",
  "echo 'Dependencies installed successfully'"
]

[start]
workDir = "backend"
# Use exec for proper signal handling in containers
# Using main_simple.py for working deployment without complex dependencies
cmd = "exec uvicorn src.main_simple:app --host 0.0.0.0 --port $PORT --workers 2 --log-level info --access-log"

[variables]
PYTHONUNBUFFERED = "1"
ENVIRONMENT = "production"
# Prevent WSGI detection
NIXPACKS_PYTHON_WSGI_MODULE = ""
# Disable Django collectstatic
DISABLE_COLLECTSTATIC = "1"
# Set worker count
WEB_CONCURRENCY = "2"