[providers]
python = "3.11"

[phases.setup]
workDir = "backend"
cmds = [
  "echo 'Installing Python dependencies...'", 
  "pip install --upgrade pip",
  "pip install --no-cache-dir -r requirements.txt",
  "echo 'Python path setup...'",
  "echo 'Dependencies installed successfully'"
]

[start]
workDir = "backend"
cmd = "exec uvicorn src.main:app --host 0.0.0.0 --port $PORT --log-level debug"

[variables]
PYTHONUNBUFFERED = "1"
ENVIRONMENT = "production"
PYTHONPATH = "/app/backend:/app/backend/src"
NIXPACKS_PYTHON_WSGI_MODULE = ""
DISABLE_COLLECTSTATIC = "1"
WEB_CONCURRENCY = "2"