# Nixpacks configuration for Railway deployment
# Deploys FastAPI app from backend/ subdirectory

[providers]
python = "3.11"

[build]
# Set working directory to backend subdirectory
workDir = "backend"

[phases.setup]
# Ensure we have the latest pip and install dependencies
cmds = [
  "pip install --upgrade pip setuptools wheel",
  "pip install -r requirements.txt"
]

[phases.build]
# No additional build steps needed for FastAPI
cmds = []

[start]
# Start the FastAPI application with production settings
# Use gunicorn with uvicorn workers for better production performance
cmd = "gunicorn main:app -w 2 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT"

[variables]
# Python configuration for production
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"
PYTHON_VERSION = "3.11"

# FastAPI production settings
ENVIRONMENT = "production"
CORS_ORIGINS = "https://threadr.vercel.app,https://threadr-frontend.vercel.app,https://www.threadr.app"

# Rate limiting configuration
RATE_LIMIT_REQUESTS = "10"
RATE_LIMIT_WINDOW_HOURS = "1"

# Content limits
MAX_TWEET_LENGTH = "280"
MAX_CONTENT_LENGTH = "10000"