# Railway deployment configuration - FIXED PATHS
providers = ["python"]

[phases.setup]
# Only install dependencies in setup phase - don't try to access source files
nixPkgs = ["python311"]
cmds = [
  "echo '=== SETUP PHASE: Installing Python dependencies ==='",
  "python --version",
  "pip install --upgrade pip",
  "pip install --no-cache-dir -r backend/requirements.txt",
  "echo '=== Dependencies installed successfully ==='"
]

[start]
# Start from root and specify full path
cmd = "cd backend && uvicorn src.main_minimal:app --host 0.0.0.0 --port $PORT --workers 1 --log-level info"

[variables]
PYTHONUNBUFFERED = "1"
ENVIRONMENT = "production"
# Force rebuild
DEPLOYMENT_VERSION = "2025-08-06-fix-paths"