[build]
# Railway build configuration
builder = "NIXPACKS"
buildCommand = "echo 'Building Threadr FastAPI backend...'"

[deploy]
# Deployment configuration
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

# Resource limits
numReplicas = 1

[environments.production]
# Production environment variables
variables = { ENVIRONMENT = "production" }

[environments.staging]
# Staging environment variables  
variables = { ENVIRONMENT = "staging" }