# Railway deployment configuration for Threadr backend
# This file is for reference - main config is in root railway.json and nixpacks.toml

[build]
builder = "NIXPACKS"

[deploy]
startCommand = "uvicorn main:app --host 0.0.0.0 --port $PORT --workers 2"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
# Environment variables for production
ENVIRONMENT = "production"
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"

# CORS configuration for production
# Update with your frontend domains
CORS_ORIGINS = "https://threadr.vercel.app,https://threadr-frontend.vercel.app,https://www.threadr.app"

# Rate limiting configuration
RATE_LIMIT_REQUESTS = "10"
RATE_LIMIT_WINDOW_HOURS = "1"

# Content limits
MAX_TWEET_LENGTH = "280"
MAX_CONTENT_LENGTH = "10000"

# Required: Set OPENAI_API_KEY in Railway dashboard
# OPENAI_API_KEY = "your-openai-key-here"