# FALLBACK Railway Nixpacks Configuration
# Use this if the main nixpacks.toml doesn't work
# This uses absolute paths and minimal configuration

# Force Python provider
[providers]
python = "3.11"

# Simple build phase
[phases.setup]
cmds = [
  "echo 'Installing dependencies from backend directory...'",
  "cd backend && pip install --upgrade pip",
  "cd backend && pip install --no-cache-dir -r requirements.txt",
  "echo 'Dependencies installed successfully'"
]

# Absolute path start command
[start]
cmd = "cd backend && python -m uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000} --workers 1 --log-level debug"

# Minimal environment variables
[variables]
PYTHONUNBUFFERED = "1"
ENVIRONMENT = "production"